export const SEARCHTEXTCHANGE = 'SEARCHTEXTCHANGE';
export const SEARCHTYPECHANGE = 'SEARCHTYPECHANGE';
export const SHOWRESULTPAGE = 'SHOWRESULTPAGE';
export const HIDERESULTPAGE = 'HIDERESULTPAGE';
