export const SEARCHTEXTCHANGE = 'SEARCHTEXTCHANGE';
export const SEARCHTYPECHANGE = 'SEARCHTYPECHANGE';
export const SHOWRESULTPAGE = 'SHOWRESULTPAGE';
export const HIDERESULTPAGE = 'HIDERESULTPAGE';
export const SEARCHINDEXUPDATE = 'SEARCHINDEXUPDATE';
export const MYDOCSUPDATE = 'MYDOCSUPDATE';
export const ONEDOCAPIUPDATE = 'ONEDOCAPIUPDATE';
